
package duoclass.View;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author rober
 */
public class TelaPrincipalProfessor extends javax.swing.JFrame {

    

    public TelaPrincipalProfessor() {
        initComponents();
        
        
        
    }

    public void fecharTela(){
        
        WindowEvent fecharjanela = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(fecharjanela);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableTurma = new javax.swing.JTable();
        PaneMenuTurma = new javax.swing.JPanel();
        ButtonSair = new javax.swing.JButton();
        LabelNomeProfessorMenu = new javax.swing.JLabel();
        ButtonExcluirTurma = new javax.swing.JButton();
        LabelTurmas = new javax.swing.JLabel();
        ButtonCadastrarTurma1 = new javax.swing.JButton();
        LabelNomeTurmaAtual = new javax.swing.JLabel();
        ButtonVisualizarAtividade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableTurma.setRowHeight(40);
        jScrollPane1.setViewportView(TableTurma);

        PaneMenuTurma.setBackground(new java.awt.Color(51, 153, 0));

        ButtonSair.setBackground(new java.awt.Color(51, 153, 0));
        ButtonSair.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSair.setText("Sair");
        ButtonSair.setBorder(null);
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });

        LabelNomeProfessorMenu.setForeground(new java.awt.Color(0, 0, 0));
        LabelNomeProfessorMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout PaneMenuTurmaLayout = new javax.swing.GroupLayout(PaneMenuTurma);
        PaneMenuTurma.setLayout(PaneMenuTurmaLayout);
        PaneMenuTurmaLayout.setHorizontalGroup(
            PaneMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneMenuTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomeProfessorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PaneMenuTurmaLayout.setVerticalGroup(
            PaneMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneMenuTurmaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(PaneMenuTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneMenuTurmaLayout.createSequentialGroup()
                        .addComponent(LabelNomeProfessorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ButtonExcluirTurma.setBackground(new java.awt.Color(204, 0, 0));
        ButtonExcluirTurma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonExcluirTurma.setForeground(new java.awt.Color(0, 0, 0));
        ButtonExcluirTurma.setText("Excluir Turma");
        ButtonExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExcluirTurmaActionPerformed(evt);
            }
        });

        LabelTurmas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTurmas.setForeground(new java.awt.Color(0, 0, 0));
        LabelTurmas.setText("Turmas");

        ButtonCadastrarTurma1.setBackground(new java.awt.Color(51, 153, 255));
        ButtonCadastrarTurma1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonCadastrarTurma1.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCadastrarTurma1.setText("Cadastrar Turma");
        ButtonCadastrarTurma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarTurma1ActionPerformed(evt);
            }
        });

        ButtonVisualizarAtividade.setBackground(new java.awt.Color(255, 204, 0));
        ButtonVisualizarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ButtonVisualizarAtividade.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVisualizarAtividade.setText("Visualizar");
        ButtonVisualizarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVisualizarAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMenuTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNomeTurmaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ButtonCadastrarTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonExcluirTurma)
                .addGap(18, 18, 18)
                .addComponent(ButtonVisualizarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PaneMenuTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomeTurmaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrarTurma1)
                    .addComponent(ButtonExcluirTurma)
                    .addComponent(ButtonVisualizarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed

        fecharTela();
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ButtonExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExcluirTurmaActionPerformed
        
        fecharTela();
        TelaExcluirTurma telaExcluir = new TelaExcluirTurma();
        telaExcluir.setVisible(true);
    }//GEN-LAST:event_ButtonExcluirTurmaActionPerformed

    private void ButtonVisualizarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVisualizarAtividadeActionPerformed
        
        fecharTela();
        TelaAtividade telaAtividade = new TelaAtividade();
        telaAtividade.setVisible(true);
    }//GEN-LAST:event_ButtonVisualizarAtividadeActionPerformed

    private void ButtonCadastrarTurma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarTurma1ActionPerformed
        
        fecharTela();
        TelaCadastroTurma telaturma = new TelaCadastroTurma();
        telaturma.setVisible(true);
    }//GEN-LAST:event_ButtonCadastrarTurma1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarTurma1;
    private javax.swing.JButton ButtonExcluirTurma;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JButton ButtonVisualizarAtividade;
    private javax.swing.JLabel LabelNomeProfessorMenu;
    private javax.swing.JLabel LabelNomeTurmaAtual;
    private javax.swing.JLabel LabelTurmas;
    private javax.swing.JPanel PaneMenuTurma;
    private javax.swing.JTable TableTurma;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
