/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duoclass.View;

import duoclass.Model.Professor;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class TelaCadastrarProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarProfessor
     */
    public TelaCadastrarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Class = new javax.swing.JLabel();
        Duo = new javax.swing.JLabel();
        ButtonVoltarParaLogin = new javax.swing.JButton();
        LabelNomeCadastar = new javax.swing.JLabel();
        LabelSenhaCadastar = new javax.swing.JLabel();
        LabelEmailCadastar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextNomeCadastrar = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextSenhaCadastrar = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextEmailCadastrar = new javax.swing.JTextPane();
        ButtonCadastrarCadastrar = new javax.swing.JButton();
        Class1 = new javax.swing.JLabel();
        Duo1 = new javax.swing.JLabel();

        Class.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        Class.setForeground(new java.awt.Color(51, 153, 0));
        Class.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Class.setText("Class");

        Duo.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        Duo.setForeground(new java.awt.Color(0, 102, 153));
        Duo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Duo.setText("Duo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonVoltarParaLogin.setBackground(new java.awt.Color(153, 153, 153));
        ButtonVoltarParaLogin.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVoltarParaLogin.setText("Voltar");
        ButtonVoltarParaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarParaLoginActionPerformed(evt);
            }
        });

        LabelNomeCadastar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNomeCadastar.setForeground(new java.awt.Color(0, 0, 0));
        LabelNomeCadastar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeCadastar.setText("Nome");

        LabelSenhaCadastar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelSenhaCadastar.setForeground(new java.awt.Color(0, 0, 0));
        LabelSenhaCadastar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSenhaCadastar.setText("Senha");

        LabelEmailCadastar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelEmailCadastar.setForeground(new java.awt.Color(0, 0, 0));
        LabelEmailCadastar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEmailCadastar.setText("Email");

        jScrollPane1.setViewportView(TextNomeCadastrar);

        jScrollPane2.setViewportView(TextSenhaCadastrar);

        jScrollPane3.setViewportView(TextEmailCadastrar);

        ButtonCadastrarCadastrar.setBackground(new java.awt.Color(51, 153, 255));
        ButtonCadastrarCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCadastrarCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCadastrarCadastrar.setText("Cadastrar");
        ButtonCadastrarCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarCadastrarActionPerformed(evt);
            }
        });

        Class1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        Class1.setForeground(new java.awt.Color(51, 153, 0));
        Class1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Class1.setText("Class");

        Duo1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        Duo1.setForeground(new java.awt.Color(0, 102, 153));
        Duo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Duo1.setText("Duo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ButtonVoltarParaLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelNomeCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelSenhaCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEmailCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonCadastrarCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Duo1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Class1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ButtonVoltarParaLogin)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Class1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNomeCadastar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSenhaCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmailCadastar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(ButtonCadastrarCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCadastrarCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarCadastrarActionPerformed
  
        Professor professor = new Professor(TextNomeCadastrar.getText(), TextEmailCadastrar.getText(), TextSenhaCadastrar.getText());
        
        boolean resultadoValidacao = Professor.validarCadastro(professor);
        
        if(resultadoValidacao == false){
            JOptionPane.showMessageDialog(null, "Nome, senha ou email inválidos!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            TextNomeCadastrar.setText("");
            TextEmailCadastrar.setText("");
            TextSenhaCadastrar.setText("");
        }
    }//GEN-LAST:event_ButtonCadastrarCadastrarActionPerformed

    private void ButtonVoltarParaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarParaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonVoltarParaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarCadastrar;
    private javax.swing.JButton ButtonVoltarParaLogin;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Class1;
    private javax.swing.JLabel Duo;
    private javax.swing.JLabel Duo1;
    private javax.swing.JLabel LabelEmailCadastar;
    private javax.swing.JLabel LabelNomeCadastar;
    private javax.swing.JLabel LabelSenhaCadastar;
    private javax.swing.JTextPane TextEmailCadastrar;
    private javax.swing.JTextPane TextNomeCadastrar;
    private javax.swing.JTextPane TextSenhaCadastrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
