/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package duoclass.View;

import duoclass.Controller.AtividadeController;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class TelaCadastrarAtividade extends javax.swing.JFrame {

    private final String email;
    private final String senha;
    private String turma;
    
    public TelaCadastrarAtividade(String email, String senha, String turma) {
        
        this.email = email;
        this.senha = senha;
        this.turma = turma;
        
        initComponents();
    }
        public void fecharTela(){
        
        WindowEvent fecharjanela = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(fecharjanela);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonVoltarTelaAtividade = new javax.swing.JButton();
        labelTituloAtividade = new javax.swing.JLabel();
        ButtonCadastrarAtividade = new javax.swing.JButton();
        TextTituloAtividade = new javax.swing.JTextField();
        labelDescricao = new javax.swing.JLabel();
        TextDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonVoltarTelaAtividade.setBackground(new java.awt.Color(153, 153, 153));
        ButtonVoltarTelaAtividade.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVoltarTelaAtividade.setText("Voltar");
        ButtonVoltarTelaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarTelaAtividadeActionPerformed(evt);
            }
        });

        labelTituloAtividade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTituloAtividade.setText("Título da Atividade");

        ButtonCadastrarAtividade.setBackground(new java.awt.Color(51, 153, 255));
        ButtonCadastrarAtividade.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCadastrarAtividade.setText("Cadastrar");
        ButtonCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarAtividadeActionPerformed(evt);
            }
        });

        TextTituloAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTituloAtividadeActionPerformed(evt);
            }
        });

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDescricao.setText("Descrição da Atividade");

        TextDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(ButtonVoltarTelaAtividade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(ButtonCadastrarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTituloAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(TextTituloAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(TextDescricao)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ButtonVoltarTelaAtividade)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextTituloAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(ButtonCadastrarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarTelaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarTelaAtividadeActionPerformed

        fecharTela();
        TelaAtividade telaAtividade = new TelaAtividade(email,senha, turma);
        telaAtividade.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarTelaAtividadeActionPerformed

    private void ButtonCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarAtividadeActionPerformed

        String titulo = TextTituloAtividade.getText();
        String descricao = TextDescricao.getText();
        
        if(titulo == null || titulo.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "A atividade não pode ser cadastrada! ", "ERRO!", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            AtividadeController.cadastrarAtividade(titulo, descricao, turma);
        
            TextTituloAtividade.setText("");
            TextDescricao.setText("");
        } 
    }//GEN-LAST:event_ButtonCadastrarAtividadeActionPerformed

    private void TextTituloAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTituloAtividadeActionPerformed

    }//GEN-LAST:event_TextTituloAtividadeActionPerformed

    private void TextDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDescricaoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarAtividade;
    private javax.swing.JButton ButtonVoltarTelaAtividade;
    private javax.swing.JTextField TextDescricao;
    private javax.swing.JTextField TextTituloAtividade;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelTituloAtividade;
    // End of variables declaration//GEN-END:variables
}
