
package duoclass.View;

import duoclass.Controller.TurmaController;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class TelaCadastroTurma extends javax.swing.JFrame {

    private final String email;
    private final String senha;
    
    public TelaCadastroTurma(String email, String senha) {
        
        this.email = email;
        this.senha = senha;
        
        initComponents();
    }

    public void fecharTela(){
        
        WindowEvent fecharjanela = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(fecharjanela);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonVoltarTelaPrincipalProfessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ButtonCadastrarTurma = new javax.swing.JButton();
        TextNomeTurma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ButtonVoltarTelaPrincipalProfessor.setBackground(new java.awt.Color(153, 153, 153));
        ButtonVoltarTelaPrincipalProfessor.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVoltarTelaPrincipalProfessor.setText("Voltar");
        ButtonVoltarTelaPrincipalProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarTelaPrincipalProfessorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nome da Turma");

        ButtonCadastrarTurma.setBackground(new java.awt.Color(51, 153, 255));
        ButtonCadastrarTurma.setForeground(new java.awt.Color(0, 0, 0));
        ButtonCadastrarTurma.setText("Cadastrar");
        ButtonCadastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarTurmaActionPerformed(evt);
            }
        });

        TextNomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(ButtonVoltarTelaPrincipalProfessor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(TextNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(ButtonCadastrarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ButtonVoltarTelaPrincipalProfessor)
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(TextNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(ButtonCadastrarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarTelaPrincipalProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarTelaPrincipalProfessorActionPerformed
        
        fecharTela();
        TelaPrincipalProfessor telaPrincipal = new TelaPrincipalProfessor(email,senha);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarTelaPrincipalProfessorActionPerformed

    private void TextNomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeTurmaActionPerformed
        
        
    }//GEN-LAST:event_TextNomeTurmaActionPerformed

    private void ButtonCadastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarTurmaActionPerformed
    
        String nome = TextNomeTurma.getText();
        
        TurmaController.inserirTurma(nome, email, senha);
        
        if(TurmaController.verificarTurma(nome)){
            
            TextNomeTurma.setText("");
            
        }else{
            JOptionPane.showMessageDialog(null, "A turma não pode ser cadastrada! ", "ERRO!", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_ButtonCadastrarTurmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrarTurma;
    private javax.swing.JButton ButtonVoltarTelaPrincipalProfessor;
    private javax.swing.JTextField TextNomeTurma;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
