
package duoclass.View;

import duoclass.Controller.ProfessorController;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class TelaAtividade extends javax.swing.JFrame {
 
    private final String email;
    private final String senha;
    private final String turma;
    
    public TelaAtividade(String email, String senha, String turma) {
        
        this.email = email;
        this.senha = senha;
        this.turma = turma;
        
        initComponents();
    }

    public void fecharTela(){
        
        WindowEvent fecharjanela = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(fecharjanela);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneMenuAtividade = new javax.swing.JPanel();
        ButtonSairTelaAtividade = new javax.swing.JButton();
        LabelNomeProfessorMenuAtividade = new javax.swing.JLabel();
        LabelTurmaAtividade = new javax.swing.JLabel();
        LabelNomeTurmaAtividade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonVoltarTelaPrincipalProfessor = new javax.swing.JButton();
        buttonTelaCadastrarAtividade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PaneMenuAtividade.setBackground(new java.awt.Color(51, 153, 0));

        ButtonSairTelaAtividade.setBackground(new java.awt.Color(51, 153, 0));
        ButtonSairTelaAtividade.setText("Sair");
        ButtonSairTelaAtividade.setBorder(null);
        ButtonSairTelaAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairTelaAtividadeActionPerformed(evt);
            }
        });

        LabelNomeProfessorMenuAtividade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNomeProfessorMenuAtividade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LabelNomeProfessorMenuAtividadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout PaneMenuAtividadeLayout = new javax.swing.GroupLayout(PaneMenuAtividade);
        PaneMenuAtividade.setLayout(PaneMenuAtividadeLayout);
        PaneMenuAtividadeLayout.setHorizontalGroup(
            PaneMenuAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneMenuAtividadeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LabelNomeProfessorMenuAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSairTelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PaneMenuAtividadeLayout.setVerticalGroup(
            PaneMenuAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneMenuAtividadeLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(PaneMenuAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNomeProfessorMenuAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSairTelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LabelTurmaAtividade.setText("Turma: ");

        LabelNomeTurmaAtividade.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LabelNomeTurmaAtividadeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ButtonVoltarTelaPrincipalProfessor.setBackground(new java.awt.Color(153, 153, 153));
        ButtonVoltarTelaPrincipalProfessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonVoltarTelaPrincipalProfessor.setText("Voltar");
        ButtonVoltarTelaPrincipalProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarTelaPrincipalProfessorActionPerformed(evt);
            }
        });

        buttonTelaCadastrarAtividade.setBackground(new java.awt.Color(51, 153, 255));
        buttonTelaCadastrarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTelaCadastrarAtividade.setForeground(new java.awt.Color(0, 0, 0));
        buttonTelaCadastrarAtividade.setText("Cadastrar Atividade");
        buttonTelaCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTelaCadastrarAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMenuAtividade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTurmaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNomeTurmaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ButtonVoltarTelaPrincipalProfessor)
                        .addGap(98, 98, 98)
                        .addComponent(buttonTelaCadastrarAtividade)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PaneMenuAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTurmaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomeTurmaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonVoltarTelaPrincipalProfessor)
                    .addComponent(buttonTelaCadastrarAtividade))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarTelaPrincipalProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarTelaPrincipalProfessorActionPerformed
        
        fecharTela();
        TelaEscolherTurma escolherTurma = new TelaEscolherTurma(email, senha);
        escolherTurma.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarTelaPrincipalProfessorActionPerformed

    private void ButtonSairTelaAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairTelaAtividadeActionPerformed
        
        fecharTela();
    }//GEN-LAST:event_ButtonSairTelaAtividadeActionPerformed

    private void LabelNomeProfessorMenuAtividadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LabelNomeProfessorMenuAtividadeAncestorAdded

        LabelNomeProfessorMenuAtividade.setText(ProfessorController.imprimirNomeProfessor(email, senha));
    }//GEN-LAST:event_LabelNomeProfessorMenuAtividadeAncestorAdded

    private void LabelNomeTurmaAtividadeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LabelNomeTurmaAtividadeAncestorAdded
        
        LabelNomeTurmaAtividade.setText(turma);
    }//GEN-LAST:event_LabelNomeTurmaAtividadeAncestorAdded

    private void buttonTelaCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTelaCadastrarAtividadeActionPerformed
        
        fecharTela();
        TelaCadastrarAtividade cadastrarAtividade = new TelaCadastrarAtividade(email, senha, turma);
        cadastrarAtividade.setVisible(true);
    }//GEN-LAST:event_buttonTelaCadastrarAtividadeActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSairTelaAtividade;
    private javax.swing.JButton ButtonVoltarTelaPrincipalProfessor;
    private javax.swing.JLabel LabelNomeProfessorMenuAtividade;
    private javax.swing.JLabel LabelNomeTurmaAtividade;
    private javax.swing.JLabel LabelTurmaAtividade;
    private javax.swing.JPanel PaneMenuAtividade;
    private javax.swing.JButton buttonTelaCadastrarAtividade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
