
package duoclass.View;

import duoclass.Controller.TurmaController;
import duoclass.Model.Turma;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class TelaEscolherTurma extends javax.swing.JFrame {
    
    private final String email;
    private final String senha;
    private String turma;

    public TelaEscolherTurma(String email, String senha) {
        
        this.email = email;
        this.senha = senha;
        
        initComponents();
        carregarComboBox();
    }
    public void fecharTela(){
        
        WindowEvent fecharjanela = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(fecharjanela); 
    }
    
    public void carregarComboBox(){

        comboBoxTurmas.removeAllItems();

        List<String> listaTurmas = TurmaController.selecionarTurmaController(email, senha);

        for (String turma : listaTurmas) {
            comboBoxTurmas.addItem(turma);
        }

        //comboBoxTurmas.setSelectedIndex(-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltarPrincipal = new javax.swing.JButton();
        labelEscolherTurma = new javax.swing.JLabel();
        comboBoxTurmas = new javax.swing.JComboBox<>();
        buttonVisualizarAtividade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonVoltarPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        buttonVoltarPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltarPrincipal.setText("Voltar");
        buttonVoltarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarPrincipalActionPerformed(evt);
            }
        });

        labelEscolherTurma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEscolherTurma.setText("Escolha a turma que deseja visualizar as atividade");

        comboBoxTurmas.setBackground(new java.awt.Color(51, 153, 0));
        comboBoxTurmas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxTurmas.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxTurmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboBoxTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTurmasActionPerformed(evt);
            }
        });

        buttonVisualizarAtividade.setBackground(new java.awt.Color(51, 153, 255));
        buttonVisualizarAtividade.setForeground(new java.awt.Color(0, 0, 0));
        buttonVisualizarAtividade.setText("Visualizar");
        buttonVisualizarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(buttonVoltarPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelEscolherTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(buttonVisualizarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(comboBoxTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonVoltarPrincipal)
                .addGap(67, 67, 67)
                .addComponent(labelEscolherTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(comboBoxTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(buttonVisualizarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarPrincipalActionPerformed

        fecharTela();
        TelaPrincipalProfessor telaPrincipal = new TelaPrincipalProfessor(email,senha);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_buttonVoltarPrincipalActionPerformed

    private void comboBoxTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTurmasActionPerformed
        
        Object turmaSelecionada = comboBoxTurmas.getSelectedItem();
        
        if(turmaSelecionada!=null){
            
            this.turma = turmaSelecionada.toString();
        }
    }//GEN-LAST:event_comboBoxTurmasActionPerformed

    private void buttonVisualizarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarAtividadeActionPerformed

        String comboBox = (String) comboBoxTurmas.getSelectedItem();
        
        if(comboBox == null || comboBox.toString().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Você não possue nenhuma turma!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
        }else{
            fecharTela();
            TelaAtividade telaAtividade = new TelaAtividade(email, senha, turma);
            telaAtividade.setVisible(true);
        }
    }//GEN-LAST:event_buttonVisualizarAtividadeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVisualizarAtividade;
    private javax.swing.JButton buttonVoltarPrincipal;
    private javax.swing.JComboBox<String> comboBoxTurmas;
    private javax.swing.JLabel labelEscolherTurma;
    // End of variables declaration//GEN-END:variables
}
